### ISSUE TITLE
Problem compiling on OSX

### ISSUE THREAD

**Issue by equinox2k** [dec1/Boost-for-Android#1]
Hi,

I have followed instructions to the letter however I'm getting an error "...failed to update x targets..."

Im not sure if due to this step...

Create a symbolic link llvm-3.5 to llvm in google's ndk-bundle/toolchains dir (This is only necessary if you want to be able to build with clang)

I tried the following in repo root...

ln -s /Users/petertribe/Documents/android-ndk-r15c/toolchains/llvm llvm-35

Can you please provide an example what should be done...

**Comment by dec1** [comment]
Hello,
Can you please provide more details of what you did, and what exactly is going wrong (maybe attach compiler output).
Thanks

**Comment by dec1** [comment]
Could also be related to https://github.com/dec1/Boost-for-Android/issues/3
Are you using ndk r16? If so could you please try with 15b.

**Comment by dec1** [comment]
In
`ln -s /Users/petertribe/Documents/android-ndk-r15c/toolchains/llvm llvm-35`

`35` should be `3.5`
