### ISSUE TITLE
abi x86 and arm64-v8a failed to build (link) in the example app

### ISSUE THREAD

**Issue by bavery22** [dec1/Boost-for-Android#10]
In build.gradle: If I set 
abiFilters 'armeabi-v7a'

the example app built.  
If I set it to 
abiFilters 'x86' or 
abiFilters 'arm64-v8a'

The build fails with a line similar to 
undefined reference to 'boost::system::detail::system_category_instance'.
I was doing this so I could run the sample on the Android emulator.

This issue:
https://github.com/boostorg/system/issues/26#issuecomment-413627799
indicates that it is a language feature problem.  I rebuilt boost with 
cxxstd=14 \
added to the run ./b2 call in build-boost.sh.  This allowed it to link for all 4 abis.

It didn't look like you were keeping a user-config.jam that I could have put the change into.  Maybe this should become the default in the shell script?

I can do a PR if you want it as a change to the script.

**Comment by dec1** [comment]
Hello and thanks for the feedback.
Which version of the ndk are you using?
Please attach your doIt.sh

**Comment by dec1** [comment]
For me Boost 1.68.0 builds fine with NDK 17c (arm64-v8a, armeabi-v7a, x86 and x86_64).

However, using the new NDK 18 causes problems. I can't tell if this is the same as what you're describing and trying your fix doesnt help.

Please can you confirm the above, or refute with a copy of the scripts that do/dont work (eg in a separate branch of your repo). 

Thanks in Advance

**Comment by bavery22** [comment]
Using NDK 17.2.4988734 on a mac,  I get the build failure with Boost 1.68.  This branch: https://github.com/bavery22/Boost-for-Android/tree/cxx14_boost168_issue_breaks_example fails to build for me (I changed gradle to have only the X86 ABI).  I also did a PR with my cxxstd=14 change to build_boost.sh which allowed the example app to build and run on the X86 emulator.
Emulator : Pixel XL API 27 Android 8.1.0 (x86)
To replicate build failure, I 
Clean Project
Make Project

**Comment by dec1** [comment]
I dont have a mac development machine available.
What hapens if you use the [precompiled binaries](https://github.com/dec1/Boost-for-Android/blob/master/prebuilt/boost_prebuilt_ndk_17.zip) and [ndk 17b](https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip) that they were built with?

**Comment by dec1** [comment]
Can you also please confirm if c++11 (ie using cxxstd=14) is enough for you?

**Comment by bavery22** [comment]
Confirmed. Removing the cppFlags "-std=c++14" from the app's build.gradle allowed me to build and run it on an x86 emulator, on a mac host build system.
I agree that keeping both the sample app and boost to the compilers default language level makes sense.  If someone needs to change it, I prefer your changing the flags approach anyway.  I'll do a different PR for the app/build.gradle change. 
Thanks!

**Comment by dec1** [comment]
Thanks for bring this to my attention and helping to sort it out.
Ive merged your pull request https://github.com/dec1/Boost-for-Android/pull/12
