### ISSUE TITLE
How do you force the build to set __ANDROID_API__ to something like 19. It defaults to 10000

### ISSUE THREAD

**Issue by bavery22** [dec1/Boost-for-Android#16]

**Comment by bavery22** [comment]
libboost_thread has some posix calls that are not defined before api 21 e.g.:
cannot locate symbol "pthread_condattr_setclock" referenced by "libboost_thread.so"...
on a kitkat (4.4) system.  How do I force the build to target a very old api?  Using defaults, I see that in boost/thread/detail/config.hpp that my __ANDROID_API__ is set to 10000 (which means android future api).

**Comment by bavery22** [comment]
Not quite.

This is not about the platforms, it's about controlling boost so that the code that calls posix pthreads doesn't get compiled in so the boost libs will work on the older OS's.  The LOWEST_ND_API_LEVEL doesn't change the default __ANDROID_API__ setting which is what the boost libs and the code in the ndk sysroots are basing their behavior off of.

This is a pointer to the pull request in boost that fixed it as well as the boost issue:
https://github.com/boostorg/thread/pull/216
https://github.com/boostorg/thread/issues/215
These are why the thread config.hpp is checking for api >= 21. Sadly my target api is 19...

So, What  I need is to set the __ANDROID_API__ define. I could probably just pass it in as a cxxflag -D__ANDROID_API__=19 if I could get jam to do so, but I am not conversant enough with jam to know how to yet.  

I think I used to be able to set this in the .mk files.

**Comment by dec1** [comment]
`LOWEST_NDK_API_LEVEL=16` in Boost-for-Android should cause boost to get built with `$NDK_DIR/platforms/android-16`.
As far as I [can tell ](https://android.googlesource.com/platform/bionic/+/master/libc/include/android/api-level.h)this where `__ANDROID_API__` gets its value.

> For the NDK, this is set by the compiler/build system based on the API level you claimed to target

So you are targeting api 16. (The boost binaries thus built should work on any device with api >= 16).

The [patch](https://github.com/boostorg/thread/pull/216) should fix the issue with `pthread_condattr_setclock`, so Im not sure what is not working for you.

Is something actually not working for you?

**Comment by dec1** [comment]
Seems like the build should define `__ANDROID_API__` 
See here](https://github.com/android-ndk/ndk/issues/407#issuecomment-306333830).
A standard android studio project (like the [test app](https://github.com/dec1/Boost-for-Android/tree/master/example_app)) has this set, but as you say when building boost with Boost-for-Android its not.

I take it everything is working fine since you defined it manually?

**Comment by bavery22** [comment]
I just managed to do a full test on a 4.4.4 device and all seems well if I define the __ANDROID_API__=19.  I have a commit in progress that allows you to set defines in doIt.sh and I have  build_boost.sh takes in the list of defines as a command line argument. Similar to how you deal with ABIs.  I'll try to submit the PR tomoro for comments.

**Comment by dec1** [comment]
OK. Thanks. Please use the "dev" branch

**Comment by bavery22** [comment]
PR done.

**Comment by bavery22** [comment]
bump?

**Comment by dec1** [comment]
Sorry for the late reply. Thanks for the pull request which has been merged.
Im not sure however if I want this in the main branch.
Even though its nice to be able to add defines like this, it does come at the cost of adding complexity to the interface, and I don't really see an application apart from defining  __ANDROID_API__.
And for  __ANDROID_API__  I think its not an ideal solution.
Ideally  __ANDROID_API__  should be set automatically based on LOWEST_NDK_API_LEVEL, which in sets the android platform level used. Im however not fully sure how/why this is handled (for 64 bit builds) where you should need a platform version higher than the current value of 16. 
Strictly speaking building a 64 bit target with a platform lower than when 64 bit support was aded to android shouldn't work. But it seems it does.
Does it always get automatically get increased to the next highest platform level that supports 64 bit builds? This needs to be clarified (independently of the __ANDROID_API__).

**Comment by bavery22** [comment]
Hmm, I see your point. 
Here's some information and a suggestion for a different approach:
info ->
Why does this work with LOWEST_NDK_API_LEVEL set to 16 for 64 bit doodads?
Because in build_tools/build-boost.sh it checks the ABI and does:
local APILEVEL=$LOWEST_NDK_API_LEVEL                              
    if [ ${ABI%%64*} != ${ABI} ]; then                                
        APILEVEL=21                                                   
    fi
so it corrects you if you are too low.
Right now this is ONLY used to set the sysroot for the boost build.

Looking into the boost code there are only 2 breakpoints for the ANDROID_API:
< 21 - this is for workarounds for old bionic stuff
< 24 for 64 bit filesystems:
boost/libs filesystems/src/operations.cpp -> // Android fully supports 64-bit file offsets only for API 24 and above.
Suggestion:
Rather than complicating the interface (you are right) what if we set 
ANDROID_API= LOWEST_NDK_API_LEVEL and where it checks to see if the ABI is 64 bit, we set 

ANDROID_API= MAX(LOWEST_NDK_API_LEVEL,21 ) (right now it just sets it to 21.

This would make the LOWEST_NDK_API_LEVEL actually work for lower levels and you could actually force boost filesystems to be 64 bit compatible as well if you want to.
We would then pass the ANDROID_API define into the boost build so it had an effect.

This seems cleaner to me and I'd be happy to do another PR if you agree with this approach. Please let me know if you like it or have a better suggestion :).

**Comment by dec1** [comment]
Thanks for looking into that and well spotted.
Then Id say the way to go would be:

set `__ANDROID_API__` to `LOWEST_NDK_API_LEVEL` at the beginning of build-boost.sh
and here

```
if [ ${ABI%%64*} != ${ABI} ]; then
APILEVEL=21
```

if APILEVEL gets set to 21 then set `__ANDROID_API__` too.

If you want to do this and create a pull request to the dev branch that would be great.
Thanks in Advance.

**Comment by dec1** [comment]
> < 24 for 64 bit filesystems:

Do you mean '>24'  ?

**Comment by bavery22** [comment]
Yes, defining it manually stops the missing symbol crash on old android
os's and it is running fine.

So, Should I go ahead with the  approach of setting __ANDROID_API__ based
on LOWEST_NDK_API_LEVEL?

-b

**Comment by dec1** [comment]
You seem to not have red my messages above?

**Comment by bavery22** [comment]
You are correct, I missed some messages since I was reading the responses on my phone email... which worked poorly.

I will go ahead and make a PR against dev sometime over the next few days doing what we outlined above.

The "< 24 " part is just how the boost code is set up. It's not something we would need to deal with. Basically, if you set the __ANDROID_API__ to 24 or more you get some additional 64 bit filesystem capabilities. Otherwise, they are not supported. I'll add a comment next to where you set the LOWEST_NDK_API_LEVEL so people know what they are picking between.

**Comment by dec1** [comment]
Great. Thanks.

**Comment by dec1** [comment]
Hello.

Ive implemented this (defined __ANDROID_API__ during the boost build) now in the branch 
[__ANDROID_API__](https://github.com/dec1/Boost-for-Android/tree/__ANDROID_API__).
Can you perhaps take a looks and see if this works for you?

Thanks in Advance
