### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by shengxingdong** [dec1/Boost-for-Android#2]
./boost/mpi/detail/mpi_datatype_primitive.hpp:28:51: fatal error: boost/serialization/detail/get_data.hpp: No such file or directory

the content of doIt.sh ：
---------------------------------------------------------------------------------------
# Specify the path to boost src dir 
BOOST_SRC_DIR=/home/sindo/Downloads/boost_1_64_0

# Specify the version of boost in the source dir
BOOST_VERSION=1.64.0

# Specify path to (Google) Ndk
GOOGLE_DIR=/home/sindo/Downloads/ndk/android-ndk-r15c

# Dont modify
export ANDROID_NDK_ROOT=$GOOGLE_DIR

# Modify if desired
# log file where build messages will be stored
logFile=build_out.txt
rm $logFile

# the build script writes some extra info to this file if its defined (but will be in "split" across different dirs)
#export NDK_LOGFILE=ndk_log_out.txt

./build_tools/build-boost.sh --version=1.64.0 --stdlibs="gnu-4.9" --abis="armeabi-v7a"  --ndk-dir=$ANDROID_NDK_ROOT --build-dir="/home/sindo/Downloads/boost_1_64_0/build" --linkage="static" --verbose $BOOST_SRC_DIR  2>&1 | tee -a $logFile 
# ./build_tools/build-boost.sh --version=1.64.0 --stdlibs="gnu-4.9" --abis="armeabi-v7a"  --ndk-dir=$ANDROID_NDK_ROOT --linkage="shared" --verbose $BOOST_SRC_DIR  2>&1 | tee -a $logFile

---------------------------------------------------------------------------------------------------------------------

**Comment by dec1** [comment]
https://svn.boost.org/trac10/ticket/12723

**Comment by dec1** [comment]
seems to be a new bug in boost.
Maybe you could try building a previous version of boost eg 1.63)

**Comment by dec1** [comment]
Which version of the ndk did you use?

**Comment by dmoran-epages** [comment]
ll
