### ISSUE TITLE
Circular Buffer Issues (all builds and NDK versions)

### ISSUE THREAD

**Issue by seanh1986** [dec1/Boost-for-Android#20]
I have been experimenting with different boost build versions and different android NDK versions to try and get boost::circular_buffer to work properly without much luck.

I have experimented with building my own, but have also experimented with using the prebuilt releases (e.g., https://github.com/dec1/Boost-for-Android/releases).

![image](https://user-images.githubusercontent.com/15824440/58659487-0f7b9f80-82f1-11e9-9c54-065873e55d0c.png)

I have experimented with various different built configurations but my current setup is the following.

CMake: 3.14.4
Android NDK: 19c
Android Gradle Plugin version: 3.4.1
Gradle version: 5.1.1
C++ compiler: Clang
C++ version: 14 (also tried 17)
OS: Windows

Note that I can import boost::circular_buffer and use various different methods but some of the boost classes themselves seem to me missing imports

Any help is greatly appreciated!

**Comment by seanh1986** [comment]
@dec1 Have you been able to test circular_buffer using android 19c and release ndk_19c_boost_1.69.0 ?

**Comment by dec1** [comment]
Sorry. I cant really help you with this.
