### ISSUE TITLE
Script fails at ./bootstrap.sh --with-toolset=cc

### ISSUE THREAD

**Issue by Tsakirogf** [dec1/Boost-for-Android#21]
I am trying to build boost_1_69 using latest ndk(20.0.5594570), which is the one that my Android Studio uses. My build stops early with the following message. I was also unable to find  'bootstrap.log' that is referred to the message.

> HOST_OS=linux
> HOST_EXE=
> HOST_ARCH=x86_64
> HOST_TAG=linux-x86_64
> HOST_NUM_CPUS=4
> BUILD_NUM_CPUS=8
> Checking whether the compiler generates 32-bit binaries...gcc -c -o /tmp/ndk-fotis/tmp/tests/test-15553.o /tmp/ndk-fotis/tmp/tests/test-15553.c
> no
> Building Boost boost_1_69_0 armeabi-v7a libraries (C++ stdlib: llvm)
> Copying directory:
>   from /home/fotis/Android/boost_1_69_0/boost_1_69_0
>   to /tmp/ndk-fotis/tmp/build-15553/build-boost/armeabi-v7a/llvm/src
>  COMMAND: mkdir /tmp/ndk-fotis/tmp/build-15553/build-boost/armeabi-v7a/llvm/host-bin
>  COMMAND: ./bootstrap.sh --with-toolset=cc
> Building Boost.Build engine with toolset cc...
> Failed to build Boost.Build build engine
> Consult 'bootstrap.log' for more details
> ERROR: Could not bootstrap Boost build
 PS : Do I need all of armeabi-v7a, arm64-v8a, x86, x86_64?

**Comment by dec1** [comment]
Did you apply the patch to boost described here?

https://github.com/boostorg/asio/pull/91

**Comment by dec1** [comment]
Your bootstrap.log should be in 
/tmp/ndk-fotis

**Comment by Tsakirogf** [comment]
Seems to build now, thanks!  :)

**Comment by dec1** [comment]
Great. Youre welcome
