### ISSUE TITLE
Build debug binaries

### ISSUE THREAD

**Issue by ki82** [dec1/Boost-for-Android#23]
It would be useful if it is possible to build debug binaries of boost instead of only release.
Preferable by a command line flag that lets you choose between debug/release and defaults to release.

If there is no flag, is it possible to manually make a debug build by some small modifications of the script? Any guidance would be appreciated.

**Comment by dec1** [comment]
Hello.

Adding `variant=debug` as a parameter fo b2 in [build.sh](https://github.com/dec1/Boost-for-Android/blob/3d55a809493d241cd7d4c3bec5ef8c519aebad42/build.sh#L335) should do the trick.

eg.
``` 
....
abi=$abi  \
.....
 ```
-> 
``` 
.....
variant=debug    \
abi=$abi  \
.....
 ```
