### ISSUE TITLE
where should I put the headers/libraries?

### ISSUE THREAD

**Issue by aaronRong** [dec1/Boost-for-Android#24]
Hi dec1,
I have built the result with static and shared libraries in install/ folder, and I put the headers into <{NDK_dir}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include>, and put libraries into <{NDK_dir}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/29>, x86_64 is my android emulator processor architecure, 29 is the android API version I want to user, NDK version is r21. But the result seems my project can find the header, but cannot find *.so
Are include and libraries folder right, thanks a lot.

**Comment by dec1** [comment]
Hello.
You dont need to copy anything into NDK_DIR.

Please see the [sample app](https://github.com/dec1/Boost-for-Android/tree/master
You should be able to just "open" it with Android studio.
It shows you exactly where you need to specify headers, libs etc

**Comment by dec1** [comment]
You dont have to _put_ them anywhere.  You just make sure your project "points" to the where ever they are.
See the example app eg [here](https://github.com/dec1/Boost-for-Android/blob/3d55a809493d241cd7d4c3bec5ef8c519aebad42/example_app/local.properties#L9) and [here](https://github.com/dec1/Boost-for-Android/blob/3d55a809493d241cd7d4c3bec5ef8c519aebad42/example_app/app/build.gradle#L3).
Based on the default the build [build location](https://github.com/dec1/Boost-for-Android/tree/3d55a809493d241cd7d4c3bec5ef8c519aebad42#build-directly-on-your-linux-machine)
