### ISSUE TITLE
missing boost::asio::ssl::context::tlsv13_compatible

### ISSUE THREAD

**Issue by qzcsfchh** [dec1/Boost-for-Android#25]
the original error message is:
```
error: no member named 'tlsv13_compatible' in
      'boost::asio::ssl::context'
```
boost version: 1.68.0
comparison between pre-build products of `Boost-for-Android` and the `official src code`:
![image](https://user-images.githubusercontent.com/17892408/174241687-b529420e-8a6c-40de-9c49-57223a6aacf2.png)

**Comment by dec1** [comment]
Please try with Boost 1.72.0

**Comment by qzcsfchh** [comment]
Thanks for reply! 
After I change Boost products version from 1.68.0 to 1.72.0 the above issue was solved but a new compile error occurred:
```
/Users/qzcsfchh/workspace/cpp_ws/Boost/ndk_21_boost_1.72.0/include/boost/asio/impl/executor.hpp:179:22: error: no member named
      'context' in 'std::__ndk1::reference_wrapper<boost::asio::io_context>'
    return executor_.context();
           ~~~~~~~~~ ^
```

Well, the context is that I have a C++ library depends on **libboost_system.a** which is build out of Boost V1.68.0 src code using the following commands:
```
    ./bootstrap.sh --with-libraries=system --with-toolset=clang
    ./b2 -j4 link=static cxxflags=-fPIC install --prefix=${boost_dir}
```
this compiles and works OK on my dev machine, but now I want to compile it for my android project.

**Comment by dec1** [comment]
Hello.
Im not sure exactly what your setup is. There seems to be some mixup on your side with boost versions and libraries. 
You need to build boost on a dev  (desktop) machine. You build it however for android (and copy the binaries with your app as necessary to the destination android phone to deploy your app). 
You should be careful not to mix libraries and/or headers built for android and those for a desktop pc.
I suggest you do  a clean rebuild of everything following my readme as close as possible, and test the sample app I provide.
