### ISSUE TITLE
ls: cannot access 'Boost-for-Android/build/install/libs/arm64-v8a': No such file or directory

### ISSUE THREAD

**Issue by wwdok** [dec1/Boost-for-Android#27]
I am building it on Windows, i changed `do.sh` to:
![image](https://user-images.githubusercontent.com/43233772/182361910-3a8f5550-93ff-4e30-aa02-0a1b7e4c6246.png)
execute `do.sh`, it throw errors:
![image](https://user-images.githubusercontent.com/43233772/182362265-a6ec5b52-5982-43e8-bcb7-6ce30d7596ca.png)
I checked the `D:\Dependency\Boost-for-Android\build\install`, found there is only a `include` folder
I look into the code, find the erroe occurs at [here](https://github.com/dec1/Boost-for-Android/blob/f1517991e6daa4156b73b659e8c0f7b001479aba/__build.sh#L269). 
I am wondering when was `boost_for_android/build/install/libs/ABI_NAME` created

**Comment by dec1** [comment]
Hello 

> I am building it on Windows, i changed `do.sh` to: ![image](https://user-images.githubusercontent.com/43233772/182361910-3a8f5550-93ff-4e30-aa02-0a1b7e4c6246.png) execute `do.sh`, it throw errors: ![image](https://user-images.githubusercontent.com/43233772/182362265-a6ec5b52-5982-43e8-bcb7-6ce30d7596ca.png) I checked the `D:\Dependency\Boost-for-Android\build\install`, found there is only a `include` folder I look into the code, find the erroe occurs at [here](https://github.com/dec1/Boost-for-Android/blob/f1517991e6daa4156b73b659e8c0f7b001479aba/__build.sh#L269). I am wondering when was `boost_for_android/build/install/libs/ABI_NAME` created

Building on windows is only officially supported via docker or virtual machines. But MingGW should work without much trouble too (I just havent had the time to test it).

The error message seems to indicate it just cant delete/create the dirs where it wants to put the built files. I recommend uncommenting the lines you [quoted](https://github.com/dec1/Boost-for-Android/blob/f1517991e6daa4156b73b659e8c0f7b001479aba/__build.sh#L269)  and get more info. Maybe its a user permission issue or some other problem with the path (mingw access to the windows dir) etc

**Comment by dec1** [comment]
> BTW, i see in example-app, it add specific boost module, how to all all of boost module ?

You would need to add each (dynamic) library individually.
If you want all, it might be easier to use the static libs

**Comment by dec1** [comment]
Glad you got the prebuilt libs working.

If you want to sort out building yourself, I would suggest modifying the script so that you isolate exactly the step that causes the problem. (By commenting out lines starting esp at the end of `__build.sh`). Also try reenabling some debug info eg by uncommenting lines like:
` #     echo "checking file " $Del_File`
You could also look in the ${BUILD_DIR}/build.log).  


is the file `version_ndk.hpp` getting written correctly ?

Its either trying to write to a dir that isnt there or create one that it doesnt have permission to write into. You just have to figure out which and why.

**Comment by dec1** [comment]
I think. I see where the root cause might be:
In `do.sh`  you have left"`LINKAGES`" is empty. You need to specify here whether you want static, dynamic or both kinds of libs

**Comment by dec1** [comment]
Seems you are using ndk version 21?
This could be  a problem with boost (build) itself calling the clang in this ndk with a parameter it [doesnt understand](https://github.com/boostorg/build/issues/367).
Please try teh boost and ndk (versions) combination in my [latest release](https://github.com/dec1/Boost-for-Android/releases)

**Comment by dec1** [comment]
Yes, each boost and ndk version may have their own bugs and quirks. IN general its not possible to combine arbitrary versions (without manual intervention). Some boost versions eg [1.71.0](https://github.com/boostorg/build/issues/385#issuecomment-485435009) need code adaptations before they build properly. 
I try to support the latest ndk with the latest boost, in regular intervals.

**Comment by dec1** [comment]
Were you able to build with MinGW?
