### ISSUE TITLE
Not able to build boost with bzip2 android prebuilt library

### ISSUE THREAD

**Issue by gopaladhith** [dec1/Boost-for-Android#28]
I am trying to add bzip2 dependency to boost for iostreams using BZIP2_NAME, BZIP2_LIBRARY_PATH AND BZIP2_INCLUDE but when i build boost it says bzip2 : no. Not sure whether i am doing something wrong any help would be appreciated.

Thanks in advance.

**Comment by dec1** [comment]
Hello.
Sounds like you don't have bzip installed (or at least boost can't find it). Try doing so, and if after you are still having problems, please describe exactly what you are doing.
Best Wishes

**Comment by gopaladhith** [comment]
Hello,
First sorry for the late response, but i have done all the steps mentioned in your docker file even then b2 build was not able to find bzip. Then i tried doing the steps mentioned in https://www.boost.org/doc/libs/1_81_0/tools/build/doc/html/index.html#bbv2.reference.tools that also did not work.
But will again investigate as to why b2 is not able to find bzip. Meanwhile if you have any points kindly provide.
And i am not an expert in buils(JFYI).

**Comment by dec1** [comment]
Hello.
Many features are are not enabled by default, but are optional and need to be configured and/or found on **your** system when the boost build is happening.

Please ensure you download and build bzip, and then tell boost where it is. 
See for example [here](https://stackoverflow.com/questions/7282645/how-to-build-boost-iostreams-with-gzip-and-bzip2-support-on-windows)

**Comment by gopaladhith** [comment]
Hello,
Yes i tried this, out of these 2 approaches described in that answer only building from source(**Option 1 (straight from source)**) includes the bzip2 but then in runtime, when using the boost_iostreams library it throws a different error saying its not able to locate BZ2_bzCompressEnd but libboost_bzip2 is present. So then i tried to use the prebuilt inclusion method for bzip2 but that did not work. Mainly i wanted to check with you about this point because your pre-built boost libraries does not cause this issue so i wanted to find whats going wrong in my build.

**Comment by dec1** [comment]
Im afraid I cant really help you unless I know exactly what you are doing.

**Comment by gopaladhith** [comment]
Ok, i modify your __build.sh file and add the -s BZIP2_SOURCE parameter to the .b2 execution. When this is executed the bzip2 source is picked  by boost build and a corresponding libboost_bzip2.so is generated. But in runtime the libboost_iostreams is not able to find a symbol inside this libboost_bzip2.so i believe(i will have to investigate this futher).
Since this is causing a runtime issue i tried including my own bzip2 library(pre-built for android) by adding these params (-s BZIP2_BINARY=libbz2 -s BZIP2_INCLUDE=C:/Sys/bzip2-1.0.6 -s BZIP2_LIBPATH) to your __build.sh file's .b2 execution but this does not take the bzip2 libs (i am saying this because when boost build is invoked it says bzip2 : no).
So this is where i am actually stuck and i am trying to figure out the issue here.

If my explanation is not clear do let me know what more is required.

**Comment by dec1** [comment]
> But in runtime the libboost_iostreams is not able to find a symbol inside this libboost_bzip2.so i believe(i will have to investigate this futher).

Please do, and give me the details of what youre calling and what exactly the output is

**Comment by dec1** [comment]
Very glad it worked for you.

It would be very nice if you could create a branch where you make any changes needed to get this working (including any explanations in comments), and open a pull request (on the _**dev** branch_).

Cheers

**Comment by gopaladhith** [comment]
Sure will commit the changes and provide doc for the same.

**Comment by gopaladhith** [comment]
@dec1 Can you grant me permission to this repository, so that i can create a branch and raise a PR.

**Comment by dec1** [comment]
Hello.

 The best is if you

-  [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) of my repo.
- in your fork create a branch called _bzip_support_ (based on  _dev_)
- make the (minimal but sufficient) changes in _bzip_support_
- open a pull request from you _bzip_support_ to my _dev_

Thanks in advance.

**Comment by gopaladhith** [comment]
Created PR - https://github.com/dec1/Boost-for-Android/pull/29

**Comment by dec1** [comment]
Thank you!

**Comment by gopaladhith** [comment]
> Thank you!

Welcome :)
