### ISSUE TITLE
symbolic link llvm-3.5 to llvm in google's ndk-bundle/toolchains

### ISSUE THREAD

**Issue by dmxraj** [dec1/Boost-for-Android#4]
_Create a symbolic link llvm-3.5 to llvm in google's ndk-bundle/toolchains dir (This is only necessary if you want to be able to build with clang)_

Can you provide an example here.

Thanks.

**Comment by dec1** [comment]
> cd path_to_ndk_toolchains_dir

 ln -s ./llvm ./llvm-3.5
