### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by awachner** [dec1/Boost-for-Android#6]
Hello,
thank you for sharing this project.
I try to build the libraries using cygwin to run the script file, but it fails. I get the following error messages:

ERROR: Unsupported HOST_TAG: cygwin-x86_64
Please update 'prepare_host_flags' in build/tools/prebuilt-common.sh
Checking whether the compiler generates 32-bit binaries...gcc -c -o /tmp/ndk-anton/tmp/tests/test-2600.o /tmp/ndk-anton/tmp/tests/test-2600.c
no
Building Boost 1.65.1 armeabi-v7a libraries (C++ stdlib: gnu-4.9)
Copying directory: 
  from /cygdrive/c/Users/anton/Downloads/boost_1_65_1/1.65.1
  to /tmp/ndk-anton/tmp/build-2600/build-boost/armeabi-v7a/gnu-4.9/src

How to run the script on Windows correctly?

**Comment by dec1** [comment]
Sorry building on windows isnt officially supported. Using cygwin should work but if it doesnt, maybe you could investigate and propose a solution yourself.

Failing that, I suggest you install virtialbox on windows, create a linux virtual machine and use this together with my scripts to build boost. The resulting binaries can then be copied to windows and used from then on as if you had built on windows to start with (theyre cross compiled for android).
